---
kind: pipeline
type: exec
name: Fuu Local deploy

steps:
- name: Prepare build environment
  commands:
  - /usr/local/go/bin/go install github.com/google/wire/cmd/wire@latest
- name: Transpile frontend
  commands:
  - cd frontend
  - pnpm i
  - pnpm build
- name: Compile backend
  commands:
  - CGO_ENABLED=1 /usr/local/go/bin/go build -o fuu main.go
- name: Deploy testing
  commands:
  - chmod +x ./fuu
  - mv ./fuu /usr/bin/fuu
  - systemctl restart fuu

# Production build to docker hub
# ---
# kind: pipeline
# name: Fuu CI/CD Docker Pipeline (production)
# steps:
# - name: Buildx and push to docker hub
#   image: jdrouet/docker-with-buildx:stable
#   volumes:
#   - name: dockersock
#     path: /var/run
#   environment:
#     USERNAME:
#       from_secret: DOCKER_HUB_USER
#     PASSWORD:
#       from_secret: DOCKER_HUB_PASS
#   commands:
#   - sleep 60
#   - docker login -u $USERNAME -p $PASSWORD
#   - docker buildx create --use
#   - docker buildx build --push --platform linux/amd64 --tag "$USERNAME/fuu:latest" .
#   - echo "Pipeline completed!"
# trigger:
#   event:
#   - promote
#   target:
#   - production
# services:
# - name: docker
#   image: docker:dind
#   privileged: true
#   volumes:
#   - name: dockersock
#     path: /var/run
# volumes:
# - name: dockersock
#   temp: {}