kind: pipeline
type: docker
name: fuu integration pipeline

steps:
- name: build
  image: alpine
  commands:
  - apk update
  - apk add go nodejs npm gcc sqlite musl-dev
  - CGO_ENABLED=1 go build -o fuu main.go