kind: pipeline
type: docker
name: Fuu CI/CD Pipeline

steps:
- name: Buildx and push to docker hub
  image: jdrouet/docker-with-buildx:stable
  commands:
  - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
  - docker buildx create --use
  - docker buildx build --push --platform linux/amd64,linux/arm/v7 --tag "$DOCKER_HUB_USER/fuu:latest" .
  - echo "Pipeline completed!"