kind: pipeline
type: docker
name: Fuu CI/CD Pipeline

steps:
- name: Buildx and push to docker hub
  image: jdrouet/docker-with-buildx:stable
  environment:
    USERNAME:
      from_secret: DOCKER_HUB_USER
    PASSWORD:
      from_secret: DOCKER_HUB_PASS
  commands:
  - docker login -u $USERNAME -p $PASSWORD
  - docker buildx create --use
  - docker buildx build --push --platform linux/amd64,linux/arm/v7 --tag "$USERNAME/fuu:latest" .
  - echo "Pipeline completed!"